export const CARS_LIST_REQUEST = "CARS_LIST_REQUEST"
export const CARS_LIST_SUCCESS = "CARS_LIST_SUCCESS"
export const CARS_LIST_FAIL = "CARS_LIST_FAIL"

export const CARS_DELETE_REQUEST = "CARS_DELETE_REQUEST"
export const CARS_DELETE_SUCCESS = "CARS_DELETE_SUCCESS"
export const CARS_DELETE_FAIL = "CARS_DELETE_FAIL"

export const CARS_CREATE_REQUEST = "CARS_CREATE_REQUEST"
export const CARS_CREATE_SUCCESS = "CARS_CREATE_SUCCESS"
export const CARS_CREATE_FAIL = "CARS_CREATE_FAIL"
export const CARS_CREATE_RESET = "CARS_CREATE_RESET"