export const DRIVERS_LIST_REQUEST = "DRIVERS_LIST_REQUEST"
export const DRIVERS_LIST_SUCCESS = "DRIVERS_LIST_SUCCESS"
export const DRIVERS_LIST_FAIL = "DRIVERS_LIST_FAIL"

export const DRIVERS_DELETE_REQUEST = "DRIVERS_DELETE_REQUEST"
export const DRIVERS_DELETE_SUCCESS = "DRIVERS_DELETE_SUCCESS"
export const DRIVERS_DELETE_FAIL = "DRIVERS_DELETE_FAIL"

export const DRIVERS_CREATE_REQUEST = "DRIVERS_CREATE_REQUEST"
export const DRIVERS_CREATE_SUCCESS = "DRIVERS_CREATE_SUCCESS"
export const DRIVERS_CREATE_FAIL = "DRIVERS_CREATE_FAIL"
export const DRIVERS_CREATE_RESET = "DRIVERS_CREATE_RESET"