export const TRAVEL_LIST_REQUEST = "TRAVEL_LIST_REQUEST"
export const TRAVEL_LIST_SUCCESS = "TRAVEL_LIST_SUCCESS"
export const TRAVEL_LIST_FAIL = "TRAVEL_LIST_FAIL"

export const TRAVEL_EDIT_REQUEST = "TRAVEL_EDIT_REQUEST"
export const TRAVEL_EDIT_SUCCESS = "TRAVEL_EDIT_SUCCESS"
export const TRAVEL_EDIT_FAIL = "TRAVEL_EDIT_FAIL"

export const TRAVEL_DELETE_REQUEST = "TRAVEL_DELETE_REQUEST"
export const TRAVEL_DELETE_SUCCESS = "TRAVEL_DELETE_SUCCESS"
export const TRAVEL_DELETE_FAIL = "TRAVEL_DELETE_FAIL"

export const TRAVEL_CREATE_REQUEST = "TRAVEL_CREATE_REQUEST"
export const TRAVEL_CREATE_SUCCESS = "TRAVEL_CREATE_SUCCESS"
export const TRAVEL_CREATE_FAIL = "TRAVEL_CREATE_FAIL"
export const TRAVEL_CREATE_RESET = "TRAVEL_CREATE_RESET"