USE [TravelDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TravelOrders](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[CarsID] [int] NOT NULL,
	[Date] [nvarchar](100) NOT NULL,
	[Mileage] [int]NOT NULL,
	[Route] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_TravelOrders] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TravelOrders]  WITH CHECK ADD  CONSTRAINT [FK_TravelOrders_Employee] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[Employee] ([ID])
GO

ALTER TABLE [dbo].[TravelOrders] CHECK CONSTRAINT [FK_TravelOrders_Employee]
GO

ALTER TABLE [dbo].[TravelOrders]  WITH CHECK ADD  CONSTRAINT [FK_TravelOrders_Cars] FOREIGN KEY([CarsID])
REFERENCES [dbo].[Cars] ([ID])
GO

ALTER TABLE [dbo].[TravelOrders] CHECK CONSTRAINT [FK_TravelOrders_Cars]
GO