USE [master]
GO

CREATE DATABASE [TravelDB]
 
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TravelDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TravelDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TravelDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TravelDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TravelDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TravelDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TravelDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TravelDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TravelDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TravelDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TravelDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TravelDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TravelDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TravelDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TravelDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TravelDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TravelDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TravelDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TravelDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TravelDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TravelDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TravelDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TravelDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TravelDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TravelDB] SET  MULTI_USER 
GO
ALTER DATABASE [TravelDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TravelDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TravelDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TravelDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TravelDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TravelDB] SET QUERY_STORE = OFF
GO
ALTER DATABASE [TravelDB] SET  READ_WRITE 
GO