CREATE DATABASE [TravelDbMVC]
 
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TravelDbMVC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TravelDbMVC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TravelDbMVC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TravelDbMVC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TravelDbMVC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TravelDbMVC] SET ARITHABORT OFF 
GO
ALTER DATABASE [TravelDbMVC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TravelDbMVC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TravelDbMVC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TravelDbMVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TravelDbMVC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TravelDbMVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TravelDbMVC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TravelDbMVC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TravelDbMVC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TravelDbMVC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TravelDbMVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TravelDbMVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TravelDbMVC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TravelDbMVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TravelDbMVC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TravelDbMVC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TravelDbMVC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TravelDbMVC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TravelDbMVC] SET  MULTI_USER 
GO
ALTER DATABASE [TravelDbMVC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TravelDbMVC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TravelDbMVC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TravelDbMVC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TravelDbMVC] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TravelDbMVC] SET QUERY_STORE = OFF
GO
ALTER DATABASE [TravelDbMVC] SET  READ_WRITE 
GO